server:
  port: 4950

#spring:
#  application:
#    name: api-gateway
#  profiles:
#    active: dev

spring:
  application:
      name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**, /v3/api-docs/authentication-service
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}
            - ApiRequestFilterMiddleWare

        - id: product-service
          uri: http://localhost:8085
          predicates:
            - Path=/product/**, /v3/api-docs/procuct-service
          filters:
            - RewritePath=/product/(?<segment>.*), /${segment}
            - ApiRequestFilterMiddleWare

        - id: account-service
          uri: http://localhost:8082
          predicates:
             - Path=/product/**, /v3/api-docs/account-service
          filters:
             - RewritePath=/product/(?<segment>.*), /${segment}
             - ApiRequestFilterMiddleWare

        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/product/**, /v3/api-docs/order-service
          filters:
            - RewritePath=/product/(?<segment>.*), /${segment}
            - ApiRequestFilterMiddleWare

        - id: payment-service
          uri: http://localhost:8086
          predicates:
            - Path=/product/**, /v3/api-docs/payment-service
          filters:
            - RewritePath=/product/(?<segment>.*), /${segment}
            - ApiRequestFilterMiddleWare

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway
      - url: /v3/api-docs/authentication-service
        name: Authentication Service

redis:
  host: localhost
  port: 6370


grpc:
  client:
    verify-token-service:
      address: static://127.0.0.1:9091
#      port: 9091
#      enableKeepAlive: true
#      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    net.devh: DEBUG
    io.grpc: DEBUG
    org.springframework.cloud.gateway: DEBUG  # Enables detailed logs for Spring Cloud Gateway
#    org.springframework.web: DEBUG           # Enables logging for Spring web components
#    org.springframework.boot: DEBUG         # Logs Spring Boot internal processes

management: # cho phép hiển thị thông tin sức khoẻ của service
  endpoints:
    web:
      exposure:
        include: '*'