server:
  port: 4950

#spring:
#  application:
#    name: api-gateway
#  profiles:
#    active: dev

spring:
  application:
      name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**, /v3/api-docs/authentication-service
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}
            - ApiRequestFilterMiddleWare
        # Uncomment to add more services
        # - id: account-service
        #   uri: http://localhost:8082
        #   predicates:
        #     - Path=/account/**, /v3/api-docs/account-service
        #   filters:
        #     - RewritePath=/account/(?<segment>.*), /${segment}
        #     - ApiRequestFilter
        # More services can be added similarly...

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway
      - url: /v3/api-docs/authentication-service
        name: Authentication Service

redis:
  host: localhost
  port: 6370


grpc:
  client:
    verify-token-service:
      address: localhost:9091
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # Enables detailed logs for Spring Cloud Gateway
#    org.springframework.web: DEBUG           # Enables logging for Spring web components
#    org.springframework.boot: DEBUG         # Logs Spring Boot internal processes

management: # cho phép hiển thị thông tin sức khoẻ của service
  endpoints:
    web:
      exposure:
        include: '*'