server:
  port: 8086

spring:
  application:
    name: payment-service
  jackson.serialization.indent_output: true
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5435/base_postgres
    username: postgres
    password: password
    #  flyway:
    #    enabled: true
    #    baseline-on-migrate: true
    #    locations: classpath:db/migration
    #    clean-disabled: true
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          boot:
            allow_jdbc_metadata_access: false
      show-sql: true
      hibernate:
        ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:29092}
    topic:
      checkoutOrder: checkout-order-topic
      updateInventory: update-inventory-topic
      notifyOrderStatus: notify-order-topic